const seedUsers=[
{id:99,name:'Admin User',username:'admin',email:'admin@skillrise.pk',password:'Admin123',role:'admin',status:'active'},
{id:10,name:'Sarah Khan',username:'sarah',email:'sarah@skillrise.pk',password:'Teacher123',role:'teacher',status:'active'},
{id:11,name:'Usman Ali',username:'usman',email:'usman@skillrise.pk',password:'Teacher123',role:'teacher',status:'active'},
{id:1,name:'Ali Student',username:'ali',email:'ali@skillrise.pk',password:'Student123',role:'student',teacherId:10,status:'active'},
{id:2,name:'Sara Student',username:'sara',email:'sara@skillrise.pk',password:'Student123',role:'student',teacherId:11,status:'active'}];
const defaultRights={dashboard:true,users:false,rights:false,courses:false,videos:false,enrollments:false,quizzes:false,assignments:false,progress:false,certificates:false,liveClasses:false,messages:false,reports:false,payments:false,settings:false,security:false};
function roleRights(role){return {...defaultRights,...(role==='admin'?Object.fromEntries(Object.keys(defaultRights).map(k=>[k,true])):{}),...(role==='teacher'?{courses:true,videos:true,enrollments:true,quizzes:true,assignments:true,progress:true,certificates:true,liveClasses:true,messages:true,reports:true}:{}),...(role==='student'?{courses:true,videos:true,quizzes:true,assignments:true,progress:true,certificates:true,liveClasses:true,messages:true,payments:true}:{})}}
let db=JSON.parse(localStorage.getItem('skillriseCompleteDB')||'null')||{users:seedUsers.map(u=>({...u,rights:roleRights(u.role)})),courses:[{id:1,title:'Freelancing Mastery',teacherId:10,status:'Published',price:5000,modules:8},{id:2,title:'Graphic Design',teacherId:11,status:'Published',price:4500,modules:6}],videos:[{id:101,title:'Freelancing Introduction',courseId:1,teacherId:10,url:'https://www.w3schools.com/html/mov_bbb.mp4',status:'Published'}],enrollments:[{id:1,studentId:1,courseId:1,status:'Active',progress:35}],quizzes:[{id:1,title:'Freelancing Basics Quiz',courseId:1,questions:10,pass:60}],assignments:[{id:1,title:'Create Upwork Profile',courseId:1,due:'2026-08-10',marks:20}],certificates:[],liveClasses:[{id:1,title:'Weekly Q&A',courseId:1,date:'2026-08-05',time:'18:00',link:'https://meet.google.com/'}],messages:[{id:1,from:10,to:1,text:'Welcome to the course',date:'2026-08-01'}],payments:[{id:1,studentId:1,courseId:1,amount:5000,method:'JazzCash',status:'Paid'}],activity:[]};
const save=()=>localStorage.setItem('skillriseCompleteDB',JSON.stringify(db));
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)]; const esc=(v='')=>String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
let currentUser=null,currentView='dashboard'; const app=$('#app'),modal=$('#modal'),mc=$('#modal-content');
const modules=[['dashboard','Dashboard','🏠'],['users','Users','👥'],['rights','User Rights','🔐'],['courses','Courses','📚'],['videos','Videos','🎬'],['enrollments','Enrollments','🧾'],['quizzes','Quizzes','❓'],['assignments','Assignments','📝'],['progress','Progress','📊'],['certificates','Certificates','🏆'],['liveClasses','Live Classes','🎥'],['messages','Communication','💬'],['reports','Reports','📈'],['payments','Payments','💳'],['settings','Mobile & Settings','⚙️'],['security','Security','🛡️']];
function allowed(k){return currentUser?.rights?.[k]||k==='dashboard'} function user(id){return db.users.find(x=>x.id==id)} function course(id){return db.courses.find(x=>x.id==id)}
function login(u,p){const found=db.users.find(x=>(x.username.toLowerCase()===u.toLowerCase()||x.email.toLowerCase()===u.toLowerCase())&&x.password===p&&x.status!=='inactive');if(!found)return false;currentUser=found;$('#login-screen').classList.add('hidden');$('#lms-shell').classList.remove('hidden');buildNav();show('dashboard');return true}
$('#login-form').onsubmit=e=>{e.preventDefault();if(!login($('#login-identity').value.trim(),$('#login-password').value))$('#login-error').textContent='Invalid login or inactive account.'};
$$('.demo-account').forEach(b=>b.onclick=()=>{$('#login-identity').value=b.dataset.u;$('#login-password').value=b.dataset.p});$('#toggle-password').onclick=()=>{let i=$('#login-password');i.type=i.type==='password'?'text':'password'};
$('#open-signup').onclick=()=>{$('#login-form').classList.add('hidden');$('#demo-accounts').classList.add('hidden');$('#signup-form').classList.remove('hidden');fillTeachers()};$('#back-login').onclick=()=>location.reload();$('#signup-role').onchange=()=>$('#teacher-select-label').classList.toggle('hidden',$('#signup-role').value!=='student');
function fillTeachers(){$('#signup-teacher').innerHTML=db.users.filter(u=>u.role==='teacher').map(u=>`<option value="${u.id}">${esc(u.name)}</option>`).join('')}
$('#signup-form').onsubmit=e=>{e.preventDefault();let pw=$('#signup-password').value;if(pw!==$('#signup-confirm-password').value)return $('#signup-message').textContent='Passwords do not match';let role=$('#signup-role').value,u={id:Date.now(),name:$('#signup-name').value,email:$('#signup-email').value,username:$('#signup-username').value,password:pw,role,status:'active',rights:roleRights(role)};if(role==='student')u.teacherId=Number($('#signup-teacher').value);db.users.push(u);save();$('#signup-message').textContent='Account created. Back to login.'};
$('#logout-button').onclick=()=>location.reload();$('#menu-toggle').onclick=()=>$('#main-nav').classList.toggle('open');
function buildNav(){$('#user-chip').innerHTML=`<strong>${esc(currentUser.name)}</strong><small>${currentUser.role}</small>`;$('#main-nav').innerHTML=modules.filter(([k])=>allowed(k)).map(([k,n,i])=>`<button data-view="${k}">${i}<span>${n}</span></button>`).join('');$$('[data-view]').forEach(b=>b.onclick=()=>show(b.dataset.view))}
function show(v){currentView=v;$('#main-nav').classList.remove('open');({dashboard,courses,videos,enrollments,quizzes,assignments,progress,certificates,liveClasses,messages,reports,payments,settings,security,users,rights}[v]||dashboard)()}
function head(title,desc,action=''){return `<section class="page-head"><div><h1>${title}</h1><p>${desc}</p></div>${action}</section>`} function stats(items){return `<div class="stats admin-stats">${items.map(([a,b])=>`<div><strong>${a}</strong><span>${b}</span></div>`).join('')}</div>`} function table(h,rows){return `<section class="panel table-wrap"><table><thead><tr>${h.map(x=>`<th>${x}</th>`).join('')}</tr></thead><tbody>${rows}</tbody></table></section>`}
function dashboard(){let role=currentUser.role;let cards=role==='admin'?[[db.users.length,'Users'],[db.courses.length,'Courses'],[db.videos.length,'Videos'],[db.payments.reduce((a,p)=>a+p.amount,0).toLocaleString(),'Revenue PKR']]:role==='teacher'?[[db.users.filter(u=>u.teacherId===currentUser.id).length,'Students'],[db.courses.filter(c=>c.teacherId===currentUser.id).length,'Courses'],[db.videos.filter(v=>v.teacherId===currentUser.id).length,'Videos'],[db.assignments.length,'Assignments']]:[[db.enrollments.filter(e=>e.studentId===currentUser.id).length,'Courses'],[db.enrollments.find(e=>e.studentId===currentUser.id)?.progress||0+'%','Progress'],[db.certificates.filter(c=>c.studentId===currentUser.id).length,'Certificates'],[db.messages.filter(m=>m.to===currentUser.id).length,'Messages']];app.innerHTML=head(`${role[0].toUpperCase()+role.slice(1)} Dashboard`,'Aap ke LMS ka central control panel.')+stats(cards)+`<div class="module-grid">${modules.filter(([k])=>allowed(k)&&k!=='dashboard').map(([k,n,i])=>`<button class="admin-tile" data-go="${k}"><b>${i} ${n}</b><span>Open module and manage records.</span></button>`).join('')}</div>`;$$('[data-go]').forEach(b=>b.onclick=()=>show(b.dataset.go))}
function users(){app.innerHTML=head('User Management','Add, edit, activate, deactivate and delete Admin, Teacher and Student accounts.','<button class="primary" id="add">+ Add User</button>')+table(['Name','Login','Role','Status','Teacher','Actions'],db.users.map(u=>`<tr><td><b>${esc(u.name)}</b><br><small>${esc(u.email)}</small></td><td>${esc(u.username)}</td><td>${u.role}</td><td>${u.status}</td><td>${u.role==='student'?esc(user(u.teacherId)?.name||'Unassigned'):'—'}</td><td><button data-edit="${u.id}">Edit</button> <button data-toggle="${u.id}">${u.status==='active'?'Deactivate':'Activate'}</button></td></tr>`).join(''));$('#add').onclick=()=>userForm();$$('[data-edit]').forEach(b=>b.onclick=()=>userForm(+b.dataset.edit));$$('[data-toggle]').forEach(b=>b.onclick=()=>{let u=user(+b.dataset.toggle);u.status=u.status==='active'?'inactive':'active';save();users()})}
function userForm(id){let u=id?user(id):{role:'student',status:'active'};mc.innerHTML=`<h2>${id?'Edit':'Add'} User</h2><form id="uf" class="form-grid"><label>Name<input name="name" value="${esc(u.name||'')}" required></label><label>Email<input name="email" value="${esc(u.email||'')}" required></label><label>Username<input name="username" value="${esc(u.username||'')}" required></label><label>Password<input name="password" value="${esc(u.password||'')}" required></label><label>Role<select name="role">${['admin','teacher','student'].map(r=>`<option ${u.role===r?'selected':''}>${r}</option>`).join('')}</select></label><label>Status<select name="status"><option>active</option><option ${u.status==='inactive'?'selected':''}>inactive</option></select></label><label>Teacher<select name="teacherId"><option value="">Unassigned</option>${db.users.filter(x=>x.role==='teacher').map(t=>`<option value="${t.id}" ${u.teacherId===t.id?'selected':''}>${t.name}</option>`).join('')}</select></label><button class="primary">Save</button></form>`;modal.classList.remove('hidden');$('#uf').onsubmit=e=>{e.preventDefault();let o=Object.fromEntries(new FormData(e.target));o.teacherId=Number(o.teacherId)||null;if(id)Object.assign(u,o,u.role!==o.role?{rights:roleRights(o.role)}:{});else db.users.push({...o,id:Date.now(),rights:roleRights(o.role)});save();modal.classList.add('hidden');users()}}
function rights(){app.innerHTML=head('User Rights','Assign module-level permissions to any account.')+table(['User','Role','Permissions'],db.users.map(u=>`<tr><td>${u.name}</td><td>${u.role}</td><td><button data-rights="${u.id}">Manage Rights</button></td></tr>`).join(''));$$('[data-rights]').forEach(b=>b.onclick=()=>rightsForm(+b.dataset.rights))}
function rightsForm(id){let u=user(id);mc.innerHTML=`<h2>${u.name} Rights</h2><form id="rf" class="rights-grid">${modules.map(([k,n])=>`<label><input type="checkbox" name="${k}" ${u.rights?.[k]?'checked':''}> ${n}</label>`).join('')}<button class="primary">Save Rights</button></form>`;modal.classList.remove('hidden');$('#rf').onsubmit=e=>{e.preventDefault();let fd=new FormData(e.target);u.rights=Object.fromEntries(modules.map(([k])=>[k,fd.has(k)]));save();modal.classList.add('hidden');buildNav();rights()}}
function courses(){let list=currentUser.role==='teacher'?db.courses.filter(c=>c.teacherId===currentUser.id):db.courses;app.innerHTML=head('Course Management','Course → Module → Chapter → Lesson structure, pricing and publishing.','<button class="primary" id="add-course">+ Add Course</button>')+`<div class="grid">${list.map(c=>`<article class="course-card"><div class="course-body"><span class="pill">${c.status}</span><h3>${c.title}</h3><p>${c.modules} modules • Teacher: ${user(c.teacherId)?.name}</p><p><b>PKR ${c.price}</b></p><button data-course-edit="${c.id}">Edit</button></div></article>`).join('')}</div>`;$('#add-course').onclick=()=>simpleForm('Course',[['title','Title'],['modules','Modules','number'],['price','Price','number']],o=>db.courses.push({id:Date.now(),teacherId:currentUser.role==='teacher'?currentUser.id:10,status:'Draft',...o}),courses);$$('[data-course-edit]').forEach(b=>b.onclick=()=>{let c=course(+b.dataset.courseEdit);simpleForm('Edit Course',[['title','Title'],['modules','Modules','number'],['price','Price','number'],['status','Status']],o=>Object.assign(c,o),courses,c)})}
function videos(){let list=currentUser.role==='student'?db.videos.filter(v=>db.enrollments.some(e=>e.studentId===currentUser.id&&e.courseId===v.courseId)):currentUser.role==='teacher'?db.videos.filter(v=>v.teacherId===currentUser.id):db.videos;app.innerHTML=head('Video Library','Upload, protect and stream course videos.','<button class="primary" id="upload">+ Upload Video</button>')+`<div class="grid">${list.map(v=>`<article class="course-card"><div class="video-thumb">▶</div><div class="course-body"><span class="pill">${v.status}</span><h3>${v.title}</h3><p>${course(v.courseId)?.title}</p><button data-watch="${v.id}">Watch</button></div></article>`).join('')}</div>`;if($('#upload'))$('#upload').onclick=()=>uploadForm();$$('[data-watch]').forEach(b=>b.onclick=()=>{let v=db.videos.find(x=>x.id==b.dataset.watch);mc.innerHTML=`<h2>${v.title}</h2><video controls controlsList="nodownload" class="player" src="${v.url}"></video>`;modal.classList.remove('hidden')})}
function uploadForm(){mc.innerHTML=`<h2>Upload Video</h2><form id="vf" class="form-grid"><label>Title<input name="title" required></label><label>Course<select name="courseId">${db.courses.map(c=>`<option value="${c.id}">${c.title}</option>`)}</select></label><label class="full">Video file<input name="file" type="file" accept="video/*" required><small>Demo limit: 200 MB. Browser session storage only.</small></label><button class="primary">Upload</button></form>`;modal.classList.remove('hidden');$('#vf').onsubmit=e=>{e.preventDefault();let f=new FormData(e.target),file=f.get('file');if(file.size>200*1024*1024)return alert('Maximum 200 MB');db.videos.push({id:Date.now(),title:f.get('title'),courseId:+f.get('courseId'),teacherId:currentUser.id,url:URL.createObjectURL(file),status:'Published'});save();modal.classList.add('hidden');videos()}}
function enrollments(){app.innerHTML=head('Enrollment Management','Manual, self, code and paid enrollment with expiry and batch access.','<button class="primary" id="add-enroll">+ Enroll Student</button>')+table(['Student','Course','Status','Progress'],db.enrollments.map(e=>`<tr><td>${user(e.studentId)?.name}</td><td>${course(e.courseId)?.title}</td><td>${e.status}</td><td>${e.progress}%</td></tr>`).join(''));$('#add-enroll').onclick=()=>simpleForm('Enroll Student',[['studentId','Student ID','number'],['courseId','Course ID','number'],['status','Status']],o=>db.enrollments.push({id:Date.now(),progress:0,...o}),enrollments)}
function quizzes(){app.innerHTML=head('Quiz & Examination','MCQs, timing, question bank, passing percentage and attempts.','<button class="primary" id="add-quiz">+ Add Quiz</button>')+table(['Quiz','Course','Questions','Passing'],db.quizzes.map(q=>`<tr><td>${q.title}</td><td>${course(q.courseId)?.title}</td><td>${q.questions}</td><td>${q.pass}%</td></tr>`).join(''));$('#add-quiz').onclick=()=>simpleForm('Create Quiz',[['title','Title'],['courseId','Course ID','number'],['questions','Questions','number'],['pass','Passing %','number']],o=>db.quizzes.push({id:Date.now(),...o}),quizzes)}
function assignments(){app.innerHTML=head('Assignments','Deadlines, submissions, marks, comments and resubmission.','<button class="primary" id="add-assignment">+ Add Assignment</button>')+table(['Assignment','Course','Due','Marks'],db.assignments.map(a=>`<tr><td>${a.title}</td><td>${course(a.courseId)?.title}</td><td>${a.due}</td><td>${a.marks}</td></tr>`).join(''));$('#add-assignment').onclick=()=>simpleForm('Create Assignment',[['title','Title'],['courseId','Course ID','number'],['due','Due Date','date'],['marks','Marks','number']],o=>db.assignments.push({id:Date.now(),...o}),assignments)}
function progress(){let es=currentUser.role==='student'?db.enrollments.filter(e=>e.studentId===currentUser.id):db.enrollments;app.innerHTML=head('Progress Tracking','Completion, watch history, quiz marks and performance.')+stats([[Math.round(es.reduce((a,e)=>a+e.progress,0)/(es.length||1))+'%','Average Progress'],[es.length,'Active Enrollments'],[db.assignments.length,'Assignments'],[db.quizzes.length,'Quizzes']])+table(['Student','Course','Progress'],es.map(e=>`<tr><td>${user(e.studentId)?.name}</td><td>${course(e.courseId)?.title}</td><td><progress value="${e.progress}" max="100"></progress> ${e.progress}%</td></tr>`).join(''))}
function certificates(){let list=currentUser.role==='student'?db.certificates.filter(c=>c.studentId===currentUser.id):db.certificates;app.innerHTML=head('Certificates','Automatic PDF-ready certificates with unique number and QR verification.','<button class="primary" id="issue-cert">+ Issue Certificate</button>')+table(['Certificate #','Student','Course','Date'],list.map(c=>`<tr><td>${c.number}</td><td>${user(c.studentId)?.name}</td><td>${course(c.courseId)?.title}</td><td>${c.date}</td></tr>`).join(''));$('#issue-cert').onclick=()=>simpleForm('Issue Certificate',[['studentId','Student ID','number'],['courseId','Course ID','number']],o=>db.certificates.push({id:Date.now(),number:'SR-'+Date.now(),date:new Date().toISOString().slice(0,10),...o}),certificates)}
function liveClasses(){app.innerHTML=head('Live Classes & Attendance','Zoom, Meet, Teams links, timetable and attendance.','<button class="primary" id="add-live">+ Schedule Class</button>')+table(['Class','Course','Date','Time','Join'],db.liveClasses.map(l=>`<tr><td>${l.title}</td><td>${course(l.courseId)?.title}</td><td>${l.date}</td><td>${l.time}</td><td><a href="${l.link}" target="_blank">Join</a></td></tr>`).join(''));$('#add-live').onclick=()=>simpleForm('Schedule Live Class',[['title','Title'],['courseId','Course ID','number'],['date','Date','date'],['time','Time','time'],['link','Meeting Link']],o=>db.liveClasses.push({id:Date.now(),...o}),liveClasses)}
function messages(){let list=currentUser.role==='admin'?db.messages:db.messages.filter(m=>m.from===currentUser.id||m.to===currentUser.id);app.innerHTML=head('Communication','Announcements, direct messages and reminders.','<button class="primary" id="new-msg">+ New Message</button>')+`<section class="panel">${list.map(m=>`<div class="student-row"><span><b>${user(m.from)?.name}</b> → ${user(m.to)?.name}<br>${esc(m.text)}</span><small>${m.date}</small></div>`).join('')}</section>`;$('#new-msg').onclick=()=>simpleForm('New Message',[['to','Recipient User ID','number'],['text','Message']],o=>db.messages.push({id:Date.now(),from:currentUser.id,date:new Date().toISOString().slice(0,10),...o}),messages)}
function reports(){app.innerHTML=head('Reports & Analytics','Users, enrollment, videos, progress, payments and audit reports.','<button class="primary" id="export">Export CSV</button>')+stats([[db.users.length,'Users'],[db.enrollments.length,'Enrollments'],[db.videos.length,'Videos'],[db.payments.reduce((a,p)=>a+p.amount,0),'Revenue']])+`<section class="panel"><h2>Available Reports</h2><p>User activity • Teacher-wise students • Course completion • Quiz results • Assignment results • Storage usage • Login history</p></section>`;$('#export').onclick=()=>{let csv='Type,Count\nUsers,'+db.users.length+'\nCourses,'+db.courses.length+'\nVideos,'+db.videos.length;let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));a.download='skillrise-report.csv';a.click()}}
function payments(){app.innerHTML=head('Payments & Invoicing','JazzCash, Easypaisa, bank transfer, coupons and teacher commission.','<button class="primary" id="add-payment">+ Record Payment</button>')+table(['Student','Course','Amount','Method','Status'],db.payments.map(p=>`<tr><td>${user(p.studentId)?.name}</td><td>${course(p.courseId)?.title}</td><td>PKR ${p.amount}</td><td>${p.method}</td><td>${p.status}</td></tr>`).join(''));$('#add-payment').onclick=()=>simpleForm('Record Payment',[['studentId','Student ID','number'],['courseId','Course ID','number'],['amount','Amount','number'],['method','Method'],['status','Status']],o=>db.payments.push({id:Date.now(),...o}),payments)}
function settings(){app.innerHTML=head('Mobile & Platform Settings','Responsive UI, language, low-internet mode, dark mode and notifications.')+`<section class="panel form-grid"><label>Language<select><option>English</option><option>Urdu</option></select></label><label>Theme<select id="theme"><option>Light</option><option>Dark</option></select></label><label><input type="checkbox"> Low Internet Mode</label><label><input type="checkbox" checked> Push Notifications</label><label><input type="checkbox"> Offline Lesson Access</label></section>`;$('#theme').onchange=e=>document.body.classList.toggle('dark',e.target.value==='Dark')}
function security(){app.innerHTML=head('Security & Audit','2FA, CAPTCHA, login limits, secure files, backups and activity logs.')+`<div class="module-grid">${['Two-Factor Authentication','CAPTCHA','Login Attempt Limit','Secure File Tokens','Automatic Logout','IP / Device Monitoring','Daily Backup','Antivirus Scan'].map(x=>`<article class="admin-tile"><b>🛡️ ${x}</b><span>Status: Configurable in production backend.</span></article>`).join('')}</div><section class="panel"><h2>Important</h2><p>This downloadable build is a browser demo. Production security requires a backend API, encrypted passwords, server-side authorization, database and private object storage.</p></section>`}
function simpleForm(title,fields,onSave,after,values={}){mc.innerHTML=`<h2>${title}</h2><form id="sf" class="form-grid">${fields.map(([n,l,t='text'])=>`<label>${l}<input name="${n}" type="${t}" value="${esc(values[n]??'')}" required></label>`).join('')}<button class="primary">Save</button></form>`;modal.classList.remove('hidden');$('#sf').onsubmit=e=>{e.preventDefault();let o=Object.fromEntries(new FormData(e.target));fields.filter(x=>x[2]==='number').forEach(x=>o[x[0]]=Number(o[x[0]]));onSave(o);save();modal.classList.add('hidden');after()}}
$$('[data-close]').forEach(b=>b.onclick=()=>modal.classList.add('hidden'));modal.onclick=e=>{if(e.target===modal)modal.classList.add('hidden')};
