"use client";
import { useMemo, useState } from "react";

type Status="Booked"|"Picked Up"|"In Transit"|"Out for Delivery"|"Delivered"|"Delivery Failed";
type Parcel={id:string;tracking:string;sender:string;receiver:string;phone:string;from:string;to:string;status:Status;rider:string;hub:string;created:string;eta:string;notes?:string};
const flow:Status[]=["Booked","Picked Up","In Transit","Out for Delivery","Delivered"];
const seed:Parcel[]=[
 {id:"1",tracking:"CMS-260813-4821",sender:"Ayesha Malik",receiver:"Hamza Khan",phone:"0300 1234567",from:"Gulberg, Lahore",to:"DHA Phase 6, Lahore",status:"Out for Delivery",rider:"Ali Raza",hub:"Lahore Central",created:"13 Aug 2026, 09:20",eta:"13 Aug 2026"},
 {id:"2",tracking:"CMS-260813-7316",sender:"Bilal Traders",receiver:"Saad Ahmed",phone:"0321 5550188",from:"Shah Alam, Lahore",to:"Bahria Town, Lahore",status:"In Transit",rider:"Usman Tariq",hub:"Thokar Hub",created:"13 Aug 2026, 10:05",eta:"14 Aug 2026"},
 {id:"3",tracking:"CMS-260812-1943",sender:"Nida Textiles",receiver:"Mariam Noor",phone:"0333 8192200",from:"Faisalabad",to:"Johar Town, Lahore",status:"Delivered",rider:"Ali Raza",hub:"Lahore Central",created:"12 Aug 2026, 14:35",eta:"13 Aug 2026"},
 {id:"4",tracking:"CMS-260813-9062",sender:"Tech Source",receiver:"Farhan Iqbal",phone:"0308 7711400",from:"Model Town, Lahore",to:"Wapda Town, Lahore",status:"Booked",rider:"Unassigned",hub:"Lahore Central",created:"13 Aug 2026, 11:42",eta:"14 Aug 2026"},
 {id:"5",tracking:"CMS-260812-5540",sender:"Zara Home",receiver:"Sana Javed",phone:"0312 4439221",from:"DHA, Lahore",to:"Cantt, Lahore",status:"Delivery Failed",rider:"Usman Tariq",hub:"Cantt Point",created:"12 Aug 2026, 16:18",eta:"14 Aug 2026",notes:"Customer unavailable · Reattempt scheduled"}
];
const Badge=({status}:{status:Status})=><span className={`badge b-${status.toLowerCase().replaceAll(" ","-")}`}>{status}</span>;
export default function CourierApp(){
 const[mode,setMode]=useState<"admin"|"track">("admin"),[page,setPage]=useState("Overview"),[parcels,setParcels]=useState(seed),[selected,setSelected]=useState(seed[0].tracking),[trackInput,setTrackInput]=useState(seed[0].tracking),[trackResult,setTrackResult]=useState<Parcel|null>(seed[0]),[toast,setToast]=useState(""),[showBook,setShowBook]=useState(false),[proof,setProof]=useState(""),[reason,setReason]=useState("Customer Unavailable");
 const parcel=parcels.find(p=>p.tracking===selected)||parcels[0];
 const counts=useMemo(()=>({total:parcels.length,delivered:parcels.filter(p=>p.status==="Delivered").length,transit:parcels.filter(p=>["Picked Up","In Transit","Out for Delivery"].includes(p.status)).length,failed:parcels.filter(p=>p.status==="Delivery Failed").length}),[parcels]);
 const notify=(s:string)=>{setToast(s);setTimeout(()=>setToast(""),2600)};
 const updateStatus=(status:Status)=>{setParcels(ps=>ps.map(p=>p.tracking===selected?{...p,status,notes:status==="Delivery Failed"?`${reason} · Reattempt scheduled`:proof?`Proof captured: ${proof}`:p.notes}:p));notify(`${selected} updated to ${status}. Public tracking synced.`)};
 if(mode==="track")return <Tracking parcels={parcels} input={trackInput} setInput={setTrackInput} result={trackResult} onTrack={()=>setTrackResult(parcels.find(p=>p.tracking.toUpperCase()===trackInput.trim().toUpperCase())||null)} onAdmin={()=>setMode("admin")}/>;
 const nav=["Overview","Shipments","Book Parcel","Rider Simulation","Hubs & Zones","Reports","Team & Roles"];
 return <div className="app-shell"><aside><Brand/><nav>{nav.map((n,i)=><button key={n} className={page===n?"active":""} onClick={()=>n==="Book Parcel"?setShowBook(true):setPage(n)}><span>{["⌂","▤","＋","⌁","⌖","▥","♙"][i]}</span>{n}{n==="Rider Simulation"&&<em>LIVE</em>}</button>)}</nav><div className="side-bottom"><button onClick={()=>setMode("track")}>◎ Customer Portal</button><div className="profile"><span>AK</span><div><b>Ahmed Khan</b><small>Administrator</small></div><button>⋮</button></div></div></aside><main><header><div><h1>{page}</h1><p>{page==="Overview"?"Thursday, 13 August 2026 · Lahore Operations":page==="Rider Simulation"?"Demonstrate the complete delivery journey":`Manage ${page.toLowerCase()}`}</p></div><div className="header-actions"><button className="ghost" onClick={()=>setMode("track")}>Public tracking ↗</button><button className="bell">♧<i/></button><button className="primary" onClick={()=>setShowBook(true)}>＋ Book parcel</button></div></header>
 {page==="Overview"&&<Overview parcels={parcels} counts={counts} open={(p)=>{setSelected(p.tracking);setPage("Rider Simulation")}} setPage={setPage}/>} {page==="Shipments"&&<Shipments parcels={parcels} open={(p)=>{setSelected(p.tracking);setPage("Rider Simulation")}}/>} {page==="Rider Simulation"&&<Rider parcel={parcel} parcels={parcels} select={setSelected} update={updateStatus} proof={proof} setProof={setProof} reason={reason} setReason={setReason}/>} {page==="Hubs & Zones"&&<Hubs/>} {page==="Reports"&&<Reports parcels={parcels} counts={counts} notify={notify}/>} {page==="Team & Roles"&&<Team/>}
 </main>{showBook&&<Booking close={()=>setShowBook(false)} save={p=>{setParcels([p,...parcels]);setShowBook(false);notify(`Parcel ${p.tracking} booked. Label generated.`)}}/>}{toast&&<div className="toast">✓ {toast}</div>}</div>
}
function Brand(){return <div className="brand"><div className="brandmark">↗</div><div><b>SwiftRoute</b><small>COURIER OPS</small></div></div>}
function Stat({icon,label,value,sub,tone}:any){return <div className="stat"><span className={`stat-icon ${tone}`}>{icon}</span><div><p>{label}</p><b>{String(value).padStart(2,"0")}</b><small className={tone}>{sub}</small></div></div>}
function Overview({parcels,counts,open,setPage}:any){return <><section className="stats"><Stat icon="▣" label="Total shipments" value={counts.total} sub="↑ 12.4% from yesterday" tone="blue"/><Stat icon="✓" label="Delivered" value={counts.delivered} sub="98.2% success rate" tone="green"/><Stat icon="↻" label="In transit" value={counts.transit} sub="Across 3 checkpoints" tone="amber"/><Stat icon="!" label="Failed attempts" value={counts.failed} sub="Needs reattempt" tone="red"/></section><section className="overview-grid"><div className="card wide"><Head title="Live shipments" sub="Real-time status across today’s operations" action="View all →" onClick={()=>setPage("Shipments")}/><ParcelTable parcels={parcels.slice(0,4)} open={open}/></div><div className="card activity"><Head title="Live activity" sub="Updates appear instantly" live/>{[["✓","Delivered","CMS-260812-1943","Mariam Noor · Ali Raza","2 min"],["↗","Out for delivery","CMS-260813-4821","DHA Phase 6 · Ali Raza","8 min"],["⌖","Arrived at checkpoint","CMS-260813-7316","Thokar Hub","24 min"],["!","Delivery failed","CMS-260812-5540","Customer unavailable","42 min"]].map((a,i)=><div className="activity-row" key={a[2]}><span className={`activity-icon a${i}`}>{a[0]}</span><div><b>{a[1]}</b><small>{a[2]}</small><p>{a[3]}</p></div><time>{a[4]}</time></div>)}</div></section><section className="lower-grid"><div className="card chart"><Head title="Delivery performance" sub="Shipments completed this week"/><div className="bars">{[58,70,64,85,74,91,78].map((v,i)=><div key={i}><span style={{height:`${v}%`}}/><small>{["Mon","Tue","Wed","Thu","Fri","Sat","Sun"][i]}</small></div>)}</div></div><div className="card quick"><Head title="Quick actions" sub="Common operations"/>{[["＋","Book a parcel","Create shipment & label"],["⌁","Rider simulation","Scan & update status"],["▥","Generate report","Export operational data"],["⌖","Manage checkpoints","Hubs, zones & routes"]].map((q,i)=><button key={q[1]} onClick={()=>setPage(i===1?"Rider Simulation":i===2?"Reports":i===3?"Hubs & Zones":"Overview")}><span>{q[0]}</span><span><b>{q[1]}</b><small>{q[2]}</small></span>›</button>)}</div></section></>}
function Head({title,sub,action,onClick,live}:any){return <div className="card-head"><div><h2>{title}</h2><p>{sub}</p></div>{live?<span className="live"><i/> LIVE</span>:action&&<button onClick={onClick}>{action}</button>}</div>}
function ParcelTable({parcels,open}:{parcels:Parcel[];open:(p:Parcel)=>void}){return <div className="table-wrap"><table><thead><tr><th>Tracking ID</th><th>Receiver</th><th>Route</th><th>Status</th><th>Rider</th><th/></tr></thead><tbody>{parcels.map(p=><tr key={p.id}><td><button className="tracking-link" onClick={()=>open(p)}>{p.tracking}</button><small>{p.created}</small></td><td><b>{p.receiver}</b><small>{p.phone}</small></td><td>{p.from.split(",")[0]} → {p.to.split(",")[0]}<small>{p.hub}</small></td><td><Badge status={p.status}/></td><td>{p.rider}</td><td><button className="more" onClick={()=>open(p)}>•••</button></td></tr>)}</tbody></table></div>}
function Shipments({parcels,open}:any){const[q,setQ]=useState("");const list=parcels.filter((p:Parcel)=>Object.values(p).join(" ").toLowerCase().includes(q.toLowerCase()));return <div className="card page-card"><div className="toolbar"><div className="search">⌕ <input placeholder="Search tracking, receiver or rider" value={q} onChange={e=>setQ(e.target.value)}/></div><select><option>All statuses</option><option>Delivered</option></select><button className="ghost">Filters</button></div><ParcelTable parcels={list} open={open}/></div>}
function Rider({parcel,parcels,select,update,proof,setProof,reason,setReason}:any){return <div className="rider-grid"><section className="card scanner"><Panel icon="⌁" title="Scan or select parcel" sub="Camera, barcode scanner, or manual lookup"/><div className="scan-box"><div><span>▦</span><b>Camera scanner ready</b><small>Point QR or barcode inside the frame</small><button>Open camera</button></div></div><label>Manual parcel selection<select value={parcel.tracking} onChange={e=>select(e.target.value)}>{parcels.map((p:Parcel)=><option key={p.id}>{p.tracking}</option>)}</select></label><div className="label-preview"><div className="qr">▦</div><div><small>TRACKING ID</small><b>{parcel.tracking}</b><div className="barcode">|||| ||| | |||| || ||| |</div></div></div></section><section className="card rider-action"><div className="panel-line"><Panel icon="↗" title="Rider action console" sub={`Acting as ${parcel.rider}`}/><Badge status={parcel.status}/></div><div className="parcel-summary"><div><small>RECEIVER</small><b>{parcel.receiver}</b><p>{parcel.phone}</p></div><div><small>DELIVERY ADDRESS</small><b>{parcel.to}</b><p>via {parcel.hub}</p></div></div><h3>Update parcel status</h3><div className="status-actions">{flow.slice(1).map(s=><button key={s} disabled={parcel.status==="Delivered"} className={s==="Delivered"?"deliver":""} onClick={()=>update(s)}>↗ {s}</button>)}</div><div className="failed"><select value={reason} onChange={e=>setReason(e.target.value)}><option>Customer Unavailable</option><option>Wrong Address</option><option>Refused</option><option>Other</option></select><button disabled={parcel.status==="Delivered"} onClick={()=>update("Delivery Failed")}>Mark not delivered</button></div><h3>Proof of delivery</h3><div className="proof-tabs">{["Photo upload","Signature","OTP: 8042"].map(x=><button key={x} className={proof===x?"selected":""} onClick={()=>setProof(x)}>{x}</button>)}</div><p className="lock-note">🔒 Final delivery locks status, timestamp and rider record.</p></section><section className="card journey"><Head title="Shipment journey" sub="Complete event history"/><Timeline parcel={parcel}/></section></div>}
function Panel({icon,title,sub}:any){return <div className="panel-title"><span>{icon}</span><div><h2>{title}</h2><p>{sub}</p></div></div>}
function Timeline({parcel}:{parcel:Parcel}){const current=parcel.status==="Delivery Failed"?3:flow.indexOf(parcel.status);return <div className="timeline">{flow.map((s,i)=><div className={i<=current?"done":""} key={s}><span>{i<current?"✓":i===current?"●":"○"}</span><div><b>{s}</b><p>{i===0?parcel.created:i<current?`13 Aug 2026 · ${10+i}:2${i}`:i===current?"Current status · live":"Awaiting update"}</p></div>{i===current&&<Badge status={parcel.status}/>}</div>)}{parcel.notes&&<div className="journey-note">{parcel.notes}</div>}</div>}
function Booking({close,save}:any){const[f,setF]=useState({sender:"",receiver:"",phone:"",from:"",to:"",rider:"Ali Raza",hub:"Lahore Central"});const go=()=>{if(!f.sender||!f.receiver||!f.to)return;save({id:String(Date.now()),tracking:`CMS-260813-${Math.floor(1000+Math.random()*9000)}`,sender:f.sender,receiver:f.receiver,phone:f.phone||"—",from:f.from||"Lahore",to:f.to,status:"Booked",rider:f.rider,hub:f.hub,created:"13 Aug 2026, now",eta:"14 Aug 2026"})};return <div className="modal-back"><div className="modal"><div className="modal-head"><div><h2>Book a new parcel</h2><p>Tracking ID, QR code and barcode are generated automatically.</p></div><button onClick={close}>×</button></div><div className="form-grid">{[["Sender name","sender"],["Receiver name","receiver"],["Receiver phone","phone"],["Pickup address","from"],["Delivery address","to"]].map(x=><label key={x[1]} className={x[1]==="to"?"span2":""}>{x[0]}<input value={f[x[1] as keyof typeof f]} onChange={e=>setF({...f,[x[1]]:e.target.value})} placeholder={`Enter ${x[0].toLowerCase()}`}/></label>)}<label>Assigned rider<select value={f.rider} onChange={e=>setF({...f,rider:e.target.value})}><option>Ali Raza</option><option>Usman Tariq</option><option>Unassigned</option></select></label><label>Origin hub<select value={f.hub} onChange={e=>setF({...f,hub:e.target.value})}><option>Lahore Central</option><option>Thokar Hub</option><option>Cantt Point</option></select></label></div><div className="modal-actions"><button className="ghost" onClick={close}>Cancel</button><button className="primary" onClick={go}>Create parcel & label</button></div></div></div>}
function Hubs(){return <div className="hub-grid">{[["Lahore Central","Gulberg III, Lahore","42 parcels"],["Thokar Hub","Multan Road, Lahore","18 parcels"],["Cantt Point","Lahore Cantt","11 parcels"]].map((h,i)=><div className="card hub" key={h[0]}><span>⌖</span><div><small>CHECKPOINT 0{i+1}</small><h2>{h[0]}</h2><p>{h[1]}</p><div><b>{h[2]}</b><em>Operational</em></div></div></div>)}<button className="add-hub">＋<b>Add checkpoint</b><small>Create a hub, zone or route point</small></button></div>}
function Reports({parcels,counts,notify}:any){const exp=(type:string)=>{const rows=parcels.map((p:Parcel)=>`${p.tracking},${p.receiver},${p.status},${p.rider},${p.hub}`).join("\n"),a=document.createElement("a");a.href=URL.createObjectURL(new Blob([`Tracking ID,Receiver,Status,Rider,Hub\n${rows}`],{type:"text/csv"}));a.download=`courier-report.${type==="Excel"?"csv":"txt"}`;a.click();notify(`${type} report exported`)};return <><section className="stats"><Stat icon="▣" label="Shipments" value={counts.total} sub="Selected period" tone="blue"/><Stat icon="✓" label="Delivered" value={counts.delivered} sub="On-time performance" tone="green"/><Stat icon="↻" label="Pending" value={counts.transit} sub="Active pipeline" tone="amber"/><Stat icon="!" label="Failed" value={counts.failed} sub="Needs attention" tone="red"/></section><div className="card report-card"><div className="card-head"><div><h2>Shipment reports</h2><p>Filter performance and export operational data</p></div><div><button className="ghost" onClick={()=>exp("PDF")}>⇩ Export PDF</button><button className="primary" onClick={()=>exp("Excel")}>⇩ Export Excel</button></div></div><div className="report-filters"><label>From<input type="date" defaultValue="2026-08-07"/></label><label>To<input type="date" defaultValue="2026-08-13"/></label><label>Zone<select><option>All Lahore</option><option>Central</option><option>South</option></select></label><button>Apply filters</button></div><ParcelTable parcels={parcels} open={()=>{}}/></div></>}
function Team(){return <div className="card page-card"><Head title="Team & role-based access" sub="Manage who can view and update operations"/><div className="team-list">{[["AK","Ahmed Khan","ahmed@swiftroute.pk","Admin","Full access"],["SM","Sara Mahmood","sara@swiftroute.pk","Manager","Operations & reports"],["UF","Umar Farooq","umar@swiftroute.pk","Staff","Booking & status updates"]].map((u,i)=><div key={u[2]}><span>{u[0]}</span><div><b>{u[1]}</b><small>{u[2]}</small></div><em className={`role r${i}`}>{u[3]}</em><p>{u[4]}</p><button>•••</button></div>)}</div></div>}
function Tracking({parcels,input,setInput,result,onTrack,onAdmin}:any){return <div className="tracking-page"><header><Brand/><button onClick={onAdmin}>Operations login →</button></header><section className="track-hero"><small>FAST · VISIBLE · RELIABLE</small><h1>Your parcel, every step<br/><em>of the way.</em></h1><p>Enter your tracking number for a live, secure view of your delivery journey.</p><div className="track-search"><input value={input} onChange={e=>setInput(e.target.value)} onKeyDown={e=>e.key==="Enter"&&onTrack()} placeholder="e.g. CMS-260813-4821"/><button onClick={onTrack}>Track shipment →</button></div><span>Try demo ID: <button onClick={()=>setInput("CMS-260813-4821")}>CMS-260813-4821</button></span></section>{result?<section className="track-result"><div className="track-summary"><div><small>TRACKING NUMBER</small><h2>{result.tracking}</h2><Badge status={result.status}/></div><div><small>ESTIMATED DELIVERY</small><b>{result.eta}</b><p>{result.status==="Delivered"?"Delivered successfully":"Expected by end of day"}</p></div><div><small>DELIVERING TO</small><b>{result.to}</b><p>Receiver: {result.receiver}</p></div></div><div className="track-content"><div className="card journey-public"><Head title="Shipment journey" sub="Updates appear here in real time" live/><Timeline parcel={result}/></div><aside className="support"><span>⌖</span><h3>Need help?</h3><p>Our support team can assist with this shipment.</p><button>Contact support</button><small>Mon–Sat · 9am–8pm PKT</small></aside></div></section>:<div className="not-found">No parcel found. Check the tracking number and try again.</div>}<footer><b>SwiftRoute Courier</b><span>Secure tracking · Lahore, Pakistan · Demo CMS</span></footer></div>}
